# The Box automated installer: boots entirely into RAM, obtains its orders
# (consent + configuration) and a storage layout, wipes the chosen disk(s) with
# disko and installs the embedded Box OS closure fully offline, then reboots.
#
# Two doors, one binary:
#   * orders present  -> box-installer resolves their storage policy (single /
#     mirror / pool) to a disko config; install proceeds unattended.
#   * no orders        -> box-installer runs the console wizard so an operator at
#     the screen picks a layout; if nobody responds it refuses and touches
#     nothing.
#
# The same module backs the ISO/USB image, the PXE netboot image, and the
# Windows-staged install — only the delivery of kernel/initrd/orders differs.
{ config, lib, pkgs, modulesPath, boxSystem, diskoPkg, boxInstaller, boxDaemon, boxCache, nixpkgsSrc, ... }:
let
  # The initrd trim (fetch the Box OS closure from the cache instead of
  # embedding it) only activates once boxCache carries a REAL key — otherwise a
  # release would ship an installer that can't fetch anything. Until then the
  # closure is embedded (fat initrd, but works offline), so main is always
  # shippable; pasting the real cachix key flips the trim on automatically.
  cacheReady = !(lib.any (lib.hasInfix "REPLACE_WITH_CACHIX_PUBLIC_KEY")
    boxCache.trustedPublicKeys);
  installScript = pkgs.writeShellApplication {
    name = "box-install";
    runtimeInputs = [
      boxInstaller
      boxDaemon
      diskoPkg
      pkgs.avahi # avahi-publish-service — the LAN beacon for unclaimed installers
      pkgs.coreutils
      pkgs.curl
      pkgs.iproute2 # `ip` — the box's address for the browser-wizard hint
      pkgs.jq
      pkgs.kmod # modprobe, for disko's mdadm/lvm module loading
      pkgs.nix
      pkgs.nixos-install-tools
      pkgs.systemd
      pkgs.util-linux
    ];
    text = ''
      # Milestones go to serial AND the wizard's progress log (browser view).
      PROG=/tmp/box-install-progress.log
      log() { echo "[box-install] $*"; echo "[box-install] $*" >> "$PROG" 2>/dev/null || true; }

      # Run both Door-2 wizards (browser + console) until one commits, then set
      # $handoff/$diskocfg from their output. $1 = optional base orders file
      # (name/wifi/key/pairing) to merge the layout into, for the "decide
      # storage on the box" flow. Either wizard exits the other via the commit
      # flag; the console wizard also self-cancels if nobody responds.
      run_wizards() {
        base_arg=""; pin=""
        if [ -n "''${1:-}" ] && [ -f "''${1:-}" ]; then
          cp "$1" /tmp/box-base.json; base_arg=/tmp/box-base.json
          # Decide-on-box: the PIN was generated by the Configurator and shown to
          # the operator, so it rides in the orders — they already have it, no
          # console needed.
          pin=$(jq -r '.setup_pin // empty' "$1" 2>/dev/null || true)
        fi
        : > "$PROG"
        rm -f /tmp/box-wizard.commit /tmp/box-wizard.done /tmp/box-install.json /tmp/box-disko.nix
        # Blank boot (no orders): random PIN, shown on the console — the operator
        # is physically present with the USB stick.
        if [ -z "$pin" ]; then
          pin=$(printf '%06d' $(( (RANDOM * 30000 + RANDOM) % 1000000 )))
        fi
        # First global IPv4, parsed with shell built-ins only (awk/head aren't
        # on the installer's PATH, and a piped head can SIGPIPE under pipefail).
        addrs=$(ip -4 -o addr show scope global 2>/dev/null || true)
        ip=""
        for tok in $addrs; do
          case "$tok" in *.*.*.*/*) ip=''${tok%%/*}; break ;; esac
        done
        url="http://''${ip:-this-box}:2693"
        echo "" > /dev/console
        echo "  ===== THE BOX — finish setup in a browser =====" > /dev/console
        echo "   open  $url" > /dev/console
        echo "   setup PIN:  $pin" > /dev/console
        echo "  ===============================================" > /dev/console
        # Beacon: announce this unclaimed machine on the LAN over mDNS so an
        # agent (or another Box's dashboard) can discover and finish it without
        # a screen — the LAN-native analog of SSH for bare metal. A per-boot
        # suffix keeps a fleet of blank machines from colliding on one name.
        # PIN-gated setup still guards the destructive endpoints; the beacon
        # only advertises "an unclaimed Box installer is here", never the PIN.
        # Bound to the wizard's lifetime: killed the moment setup commits below.
        sfx=$(printf '%04x' $((RANDOM % 65536)))
        avahi-publish-service "box-setup-$sfx · The Box" _thebox-setup._tcp 2693 \
          "vendor=thebox" "role=installer" "state=unclaimed" "pin=required" \
          >/dev/null 2>&1 &
        beacon_pid=$!
        # shellcheck disable=SC2086
        boxd install-wizard --listen 0.0.0.0:2693 \
          --orders-out /tmp/box-install.json --disko-out /tmp/box-disko.nix \
          --commit-flag /tmp/box-wizard.commit --progress "$PROG" --done /tmp/box-wizard.done \
          --pin "$pin" ''${base_arg:+--base-orders "$base_arg"} &
        wtty=/dev/tty1; [ -c "$wtty" ] || wtty=/dev/console
        # shellcheck disable=SC2086
        TERM=linux setsid -w -c box-installer wizard \
          --orders-out /tmp/box-install.json --disko-out /tmp/box-disko.nix \
          --watch-commit /tmp/box-wizard.commit --browser-url "$url" --pin "$pin" \
          ''${base_arg:+--base-orders "$base_arg"} \
          <> "$wtty" >&0 2>&0 || true
        for _ in 1 2 3 4 5; do
          [ -f /tmp/box-install.json ] && [ -f /tmp/box-disko.nix ] && break
          sleep 1
        done
        # Setup is committing (or was cancelled) — stop advertising as unclaimed.
        kill "''${beacon_pid:-}" 2>/dev/null || true
        if [ -f /tmp/box-install.json ] && [ -f /tmp/box-disko.nix ]; then
          handoff=/tmp/box-install.json
          diskocfg=/tmp/box-disko.nix
        fi
      }

      # ---- 1. Locate the orders (consent + config) ------------------------
      # Orders are always copied to RAM before anything touches a disk; in the
      # staged-from-Windows flow they live on the very disk being wiped.
      handoff=""
      diskocfg=""

      # Orders passed on the kernel command line (the curl|sh takeover): base64,
      # RAM-only, and survives the initramfs -> installer switch-root (files
      # injected into the initramfs do NOT — NixOS drops them at switch-root).
      b64=$(tr ' ' '\n' < /proc/cmdline | sed -n 's/^box\.install-b64=//p' | head -n1)
      if [ -z "$handoff" ] && [ -n "$b64" ]; then
        log "using orders from the kernel command line"
        if printf '%s' "$b64" | base64 -d > /tmp/box-install.json 2>/dev/null; then
          handoff=/tmp/box-install.json
        else
          log "failed to decode box.install-b64"
        fi
      fi
      url=$(tr ' ' '\n' < /proc/cmdline | sed -n 's/^box\.install-url=//p' | head -n1)
      if [ -z "$handoff" ] && [ -n "$url" ]; then
        log "fetching orders from $url"
        if curl -fsSL "$url" -o /tmp/box-install.json; then
          handoff=/tmp/box-install.json
        else
          log "failed to fetch $url"
        fi
      fi
      if [ -z "$handoff" ] && [ -e /dev/disk/by-label/BOX-INSTALL ]; then
        mkdir -p /run/box-handoff
        mount -o ro /dev/disk/by-label/BOX-INSTALL /run/box-handoff
        if [ -f /run/box-handoff/box-install.json ]; then
          cp /run/box-handoff/box-install.json /tmp/box-install.json
          handoff=/tmp/box-install.json
        fi
        umount /run/box-handoff || true
      fi
      # Staged installs (e.g. launched from Windows): scan every partition for
      # box-installer/box-install.json.
      if [ -z "$handoff" ] && grep -q 'box\.install-scan' /proc/cmdline; then
        mkdir -p /run/box-scan
        while read -r name type; do
          if [ "$type" != "part" ]; then continue; fi
          if mount -o ro "/dev/$name" /run/box-scan 2>/dev/null; then
            if [ -f /run/box-scan/box-installer/box-install.json ]; then
              log "found staged orders on /dev/$name"
              cp /run/box-scan/box-installer/box-install.json /tmp/box-install.json
              handoff=/tmp/box-install.json
            fi
            umount /run/box-scan || true
          fi
          if [ -n "$handoff" ]; then break; fi
        done < <(lsblk -rno NAME,TYPE)
      fi

      # ---- 2. No orders -> the console wizard (Door 2), else refuse --------
      # The wizard writes its own effective orders + disko config. It exits
      # non-zero if the operator cancels, or on its own if nobody responds
      # within a couple of minutes (headless boot with no orders) — so an
      # unattended machine that reached here by accident is never wiped.
      if [ -z "$handoff" ]; then
        log "no orders found — starting setup (screen + browser); refusing if no operator responds."
        run_wizards ""
      fi
      if [ -z "$handoff" ]; then
        log "no orders (BOX-INSTALL volume, box.install-url=, box.install-b64=, staged dir)"
        log "and no console setup completed. Refusing to touch any disk. Machine unchanged."
        exit 0
      fi

      log "using orders: $handoff"
      jq . "$handoff" > /dev/null || { log "orders are not valid JSON"; exit 1; }

      erase=$(jq -r '.erase_disk // false' "$handoff")
      if [ "$erase" != "true" ]; then
        log "orders do not set \"erase_disk\": true — refusing to wipe anything."
        exit 1
      fi

      # Consent says we may wipe this machine; this says who owns what we build.
      #
      # An unattended install runs with nobody watching, so minting a code here
      # would produce one nobody ever sees. A Box with no owner has only one way
      # left to be claimed — over the network, first-come — and it announces
      # itself on mDNS the moment it boots, which is a race a script wins
      # against a human every time. Every real producer of orders (the
      # Configurator, the image download, `boxd provision`, both wizards)
      # supplies a hash, so reaching here without one means something went
      # wrong upstream. Refuse while the machine is still intact.
      if [ -z "$(jq -r '.enrollment_code_hash // empty' "$handoff")" ]; then
        log "these orders carry no pairing code, so this Box would boot with no owner."
        log "NOTHING HAS BEEN CHANGED. Build your install at https://thebox.build/configurator/"
        log "(or run setup on the machine itself) so the Box knows who it belongs to."
        exit 1
      fi

      # Box OS boots via UEFI (systemd-boot). On a legacy-BIOS machine every
      # step below would succeed right up to installing the bootloader, which
      # means the disk is already gone by the time we find out — a machine wiped
      # and left with nothing to boot. Check first.
      if [ ! -d /sys/firmware/efi ]; then
        log "this machine booted in legacy BIOS mode, and Box OS boots via UEFI."
        log "NOTHING HAS BEEN CHANGED. Enable UEFI in the firmware settings and"
        log "run this again, or install from the USB image on older hardware."
        exit 1
      fi

      # Orders present but storage deferred ("decide on the box"): run the
      # wizards with this box's identity preloaded, so the operator picks only
      # the disk layout. The wizard rewrites $handoff with the merged orders.
      if [ "$(jq -r '.storage.layout // ""' "$handoff")" = "ask" ]; then
        log "orders defer storage to the box — starting setup with your identity preloaded."
        run_wizards "$handoff"
        if [ ! -f /tmp/box-disko.nix ]; then
          log "storage was not chosen — refusing to touch any disk. Machine unchanged."
          exit 0
        fi
      fi

      # ---- 3. Resolve the storage layout to a disko config ----------------
      # (The wizard already produced one; the pre-baked-orders path resolves the
      # storage policy — single / mirror / pool — against the real disks here.)
      if [ -z "$diskocfg" ]; then
        diskocfg=/tmp/box-disko.nix
        if ! box-installer plan --orders "$handoff" --out "$diskocfg"; then
          log "could not resolve a storage layout from the orders (see message above)."
          exit 1
        fi
      fi

      # ---- 4. Partition + format via disko --------------------------------
      # Last check before the disks go. A trimmed installer does not carry the
      # Box OS closure — it fetches it from the binary cache at install time —
      # so an unreachable cache used to be discovered AFTER the wipe, leaving a
      # machine with no OS and no way back.
      system=$(cat /etc/box/system-store-path)
      if ! nix path-info "$system" >/dev/null 2>&1; then
        log "the Box OS closure is not on this installer — checking it can be fetched ..."
        if ! nix-store --realise --dry-run "$system" >/dev/null 2>&1; then
          log "cannot reach the Box OS closure ($system)."
          log "NOTHING HAS BEEN CHANGED. Check this machine's network and DNS, then"
          log "run this again."
          exit 1
        fi
      fi

      log "partitioning with disko (this ERASES the target disk(s))"
      disko --mode destroy,format,mount --yes-wipe-all-disks \
        --root-mountpoint /mnt "$diskocfg" 2>&1 | tee -a "$PROG"

      # ---- 5. Install the Box OS closure ----------------------------------
      log "installing Box OS from $system"
      mkdir -p /mnt/etc/box
      install -m 600 "$handoff" /mnt/etc/box/install-config.json
      nixos-install --system "$system" --no-root-passwd --no-channel-copy 2>&1 | tee -a "$PROG"
      log "BOX INSTALL COMPLETE"
      : > /tmp/box-wizard.done # tell the browser wizard the install finished

      # ---- 6. Finish ------------------------------------------------------
      finish=$(jq -r '.finish // "reboot"' "$handoff")
      umount -R /mnt || true
      case "$finish" in
        poweroff) systemctl poweroff ;;
        none) log "finish=none: leaving installer running" ;;
        *) systemctl reboot ;;
      esac
    '';
  };
in
{
  networking.hostName = "box-installer";
  # The browser install wizard is served on 2693; open it so a LAN browser can
  # reach the pre-pairing setup (the installer firewall otherwise allows only
  # SSH). Transient installer environment only.
  networking.firewall.allowedTCPPorts = [ 2693 ];
  # mDNS so the blank-boot beacon (avahi-publish-service, run_wizards) can
  # advertise this unclaimed installer for agent discovery. userServices lets
  # the beacon register over avahi's D-Bus API; openFirewall (default) opens
  # 5353/udp. Transient installer environment only.
  services.avahi = {
    enable = true;
    publish = {
      enable = true;
      userServices = true;
    };
  };
  # ttyS0 last = primary console, so installer progress is visible over serial.
  boot.kernelParams = [ "console=tty0" "console=ttyS0,115200" ];
  # Load RAID/device-mapper modules in the installer so disko can *build* a
  # mirror (mdadm) or pool (LVM) at install time — separate from the installed
  # OS assembling them at boot (see hardware-appliance.nix).
  boot.kernelModules = [ "md_mod" "dm_mod" "raid0" "raid1" "raid10" ];

  # Free tty1 so the setup wizard owns the screen (Door 2). Serial stays the
  # log/primary console; the wizard only appears where there's a monitor.
  systemd.services."getty@tty1".enable = lib.mkForce false;
  systemd.services."autovt@tty1".enable = lib.mkForce false;

  # With a real cache, bake only the store *path* (unsafeDiscardStringContext
  # keeps the ~1.4 GB closure out of the initrd) and fetch it at install time —
  # the installer writes it straight to the target disk. Without one, embed the
  # closure so the installer still works fully offline.
  environment.etc."box/system-store-path".text =
    if cacheReady
    then builtins.unsafeDiscardStringContext "${boxSystem}"
    else "${boxSystem}";
  environment.systemPackages = [ installScript boxInstaller boxDaemon diskoPkg pkgs.jq ];

  # disko evaluates its config at runtime; bake nixpkgs in so that also works
  # offline.
  nix.nixPath = [ "nixpkgs=${nixpkgsSrc}" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  # Where a trimmed installer pulls the Box OS closure from (cache.nixos.org for
  # the nixpkgs deps + our platform cache for boxd/box-os paths).
  nix.settings.substituters =
    [ "https://cache.nixos.org" ] ++ lib.optionals cacheReady boxCache.substituters;
  nix.settings.trusted-public-keys =
    [ "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" ]
    ++ lib.optionals cacheReady boxCache.trustedPublicKeys;

  systemd.services.box-install = {
    description = "The Box automated installer";
    wantedBy = [ "multi-user.target" ];
    after = [ "local-fs.target" "systemd-udev-settle.service" ];
    wants = [ "systemd-udev-settle.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      StandardOutput = "journal+console";
      StandardError = "journal+console";
    };
    path = [ installScript ];
    script = "box-install";
  };
}
