//! Generate a standalone, dendritic per-box config repo from the declarative
//! config. This is the OS tier's source of truth: `box.toml` compiles to a
//! `nixosConfigurations.<id>` flake that composes the platform + hardware
//! layers with one auto-discovered module per service. Unlike nixgen's
//! lightweight content generation, this repo builds a whole NixOS system that
//! `switch-to-configuration` activates and can roll back.
//!
//! The `the-box` input is the platform: on a real Box it's the pinned update
//! channel (see the update-channel increment); for local builds it's a path or
//! git ref. Everything else is derived from the config.

use std::path::Path;

use anyhow::{Context, Result};

use crate::config::{validate_service_name, BoxConfig};
use crate::paths::Paths;
use crate::templates;
use crate::util;

/// Identity and platform binding for a generated per-box repo.
#[derive(Debug, Clone)]
pub struct HostSpec {
    /// Host id — becomes the hostname and the nixosConfigurations attr name.
    pub id: String,
    /// Flake ref for the Box platform (`the-box` input): the update channel on
    /// a real Box, or a `path:`/`git+file:` ref for local builds.
    pub platform_ref: String,
    /// Nix system double, e.g. "x86_64-linux".
    pub system: String,
}

impl HostSpec {
    pub fn new(
        id: impl Into<String>,
        platform_ref: impl Into<String>,
        system: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            platform_ref: platform_ref.into(),
            system: system.into(),
        }
    }
}

/// Host ids share the constraints of service names (they become a hostname and
/// a Nix attribute name) with the extra hostname rule that they can't be purely
/// numeric — reuse the service-name validator, which already covers the shape.
pub fn validate_host_id(id: &str) -> Result<()> {
    validate_service_name(id).with_context(|| format!("invalid host id {id:?}"))
}

fn render_flake(spec: &HostSpec) -> String {
    format!(
        r#"{{
  description = "The Box — configuration for {id} (managed by boxd; do not edit by hand)";

  # The platform is the Box's update channel: boxd, the base OS and the
  # template library, pinned. nixpkgs follows it so the whole box stays
  # coherent with the platform it was built against.
  inputs.the-box.url = "{platform_ref}";
  inputs.nixpkgs.follows = "the-box/nixpkgs";

  outputs = {{ self, nixpkgs, the-box, ... }}:
    {{
      nixosConfigurations."{id}" = nixpkgs.lib.nixosSystem {{
        system = "{system}";
        modules = [
          the-box.nixosModules.platform
          the-box.nixosModules.hardwareAppliance
          ./nodes/hosts/{id}
        ];
      }};
    }};
}}
"#,
        id = spec.id,
        platform_ref = spec.platform_ref,
        system = spec.system,
    )
}

fn render_host_module(spec: &HostSpec) -> String {
    format!(
        r#"# generated by boxd — host {id}
# Identity plus auto-discovered, box.toml-compiled service modules. Drop a
# .nix file in services/ and it joins the system on the next build.
{{ lib, ... }}:
let
  servicesDir = ./services;
  serviceModules = lib.optionals (builtins.pathExists servicesDir) (
    map (name: servicesDir + "/${{name}}") (
      builtins.filter (lib.hasSuffix ".nix") (
        builtins.attrNames (builtins.readDir servicesDir)
      )
    )
  );
in
{{
  imports = serviceModules;

  networking.hostName = "{id}";
}}
"#,
        id = spec.id,
    )
}

/// Write the whole per-box repo under `out_dir` (emptied first):
/// ```text
/// flake.nix
/// nodes/hosts/<id>/default.nix
/// nodes/hosts/<id>/services/<name>.nix        (compiled module)
/// nodes/hosts/<id>/services/<name>/www/...     (materialized content)
/// ```
pub fn write_host_repo(
    paths: &Paths,
    config: &BoxConfig,
    spec: &HostSpec,
    out_dir: &Path,
) -> Result<()> {
    validate_host_id(&spec.id)?;

    // Preserve the platform pin across regeneration: a routine deploy rewrites
    // the sources but must not silently re-resolve the channel. Only an
    // explicit `channel update` bumps flake.lock.
    let saved_lock = std::fs::read(out_dir.join("flake.lock")).ok();

    util::remove_dir_all_forced(out_dir)?;
    let host_dir = out_dir.join("nodes").join("hosts").join(&spec.id);
    let services_dir = host_dir.join("services");
    std::fs::create_dir_all(&services_dir)
        .with_context(|| format!("creating {}", services_dir.display()))?;

    std::fs::write(out_dir.join("flake.nix"), render_flake(spec))?;
    std::fs::write(host_dir.join("default.nix"), render_host_module(spec))?;

    for service in &config.services {
        validate_service_name(&service.name)?;
        let Some(template) = templates::get(&service.template) else {
            anyhow::bail!(
                "service {:?} uses unknown template {:?}",
                service.name,
                service.template
            );
        };

        // Fold the top-level domain into params so the compiled module carries
        // it, matching nixgen's fast path exactly.
        let mut params = service.params.clone();
        if let (Some(obj), Some(domain)) = (params.as_object_mut(), &service.domain) {
            obj.entry("domain")
                .or_insert_with(|| serde_json::Value::String(domain.clone()));
        }

        std::fs::write(
            services_dir.join(format!("{}.nix", service.name)),
            template.nix_module(&service.name, &params),
        )?;

        // Content: prefer the live source tree; fall back to re-materializing
        // from params (e.g. a config restored without its sources).
        let www = services_dir.join(&service.name).join("www");
        let source = paths.source_dir(&service.name);
        if source.is_dir() {
            util::copy_dir_recursive(&source, &www)?;
        } else {
            template.materialize(&params, &www)?;
        }
    }

    if let Some(lock) = saved_lock {
        std::fs::write(out_dir.join("flake.lock"), lock)?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::ServiceConfig;
    use chrono::Utc;
    use tempfile::TempDir;

    fn sample_config() -> BoxConfig {
        BoxConfig {
            services: vec![ServiceConfig {
                name: "blog".into(),
                template: "static-site".into(),
                params: serde_json::json!({ "index_html": "<h1>hi</h1>" }),
                domain: Some("blog.example.com".into()),
                public: true,
                port: None,
                created_at: Utc::now(),
            }],
            ..Default::default()
        }
    }

    #[test]
    fn generates_composable_repo() {
        let tmp = TempDir::new().unwrap();
        let paths = Paths::new(tmp.path().join("data"));
        paths.ensure().unwrap();
        let out = tmp.path().join("repo");
        let spec = HostSpec::new(
            "demo-box",
            "github:fluxoz/the-box",
            "x86_64-linux",
        );

        write_host_repo(&paths, &sample_config(), &spec, &out).unwrap();

        let flake = std::fs::read_to_string(out.join("flake.nix")).unwrap();
        assert!(flake.contains(r#"nixosConfigurations."demo-box""#));
        assert!(flake.contains("the-box.nixosModules.platform"));
        assert!(flake.contains("the-box.nixosModules.hardwareAppliance"));
        assert!(flake.contains(r#"inputs.the-box.url = "github:fluxoz/the-box""#));

        let host = std::fs::read_to_string(out.join("nodes/hosts/demo-box/default.nix")).unwrap();
        assert!(host.contains(r#"networking.hostName = "demo-box""#));

        // Compiled service module + materialized content, domain folded in.
        let module =
            std::fs::read_to_string(out.join("nodes/hosts/demo-box/services/blog.nix")).unwrap();
        assert!(module.contains(r#"services.the-box.sites."blog""#));
        assert!(module.contains("root = ./blog/www;"));
        assert!(module.contains(r#"domain = "blog.example.com";"#));
        assert_eq!(
            std::fs::read_to_string(out.join("nodes/hosts/demo-box/services/blog/www/index.html"))
                .unwrap(),
            "<h1>hi</h1>"
        );
    }

    #[test]
    fn rejects_bad_host_id() {
        assert!(validate_host_id("Good-Box").is_err());
        assert!(validate_host_id("box-1").is_ok());
    }

    #[test]
    fn preserves_flake_lock_across_regeneration() {
        let tmp = TempDir::new().unwrap();
        let paths = Paths::new(tmp.path().join("data"));
        paths.ensure().unwrap();
        let out = tmp.path().join("repo");
        let spec = HostSpec::new("demo-box", "path:/platform", "x86_64-linux");

        write_host_repo(&paths, &sample_config(), &spec, &out).unwrap();
        // A deploy must not silently re-resolve the platform pin.
        std::fs::write(out.join("flake.lock"), r#"{"pinned":"v1"}"#).unwrap();
        write_host_repo(&paths, &BoxConfig::default(), &spec, &out).unwrap();
        assert_eq!(
            std::fs::read_to_string(out.join("flake.lock")).unwrap(),
            r#"{"pinned":"v1"}"#
        );
    }
}
