//! Generate a standalone, dendritic per-box config repo from the declarative
//! config. This is the OS tier's source of truth: `box.toml` compiles to a
//! `nixosConfigurations.<id>` flake that composes the platform + hardware
//! layers with one auto-discovered module per service. Unlike nixgen's
//! lightweight content generation, this repo builds a whole NixOS system that
//! `switch-to-configuration` activates and can roll back.
//!
//! The `the-box` input is the platform: on a real Box it's the pinned update
//! channel (see the update-channel increment); for local builds it's a path or
//! git ref. Everything else is derived from the config.

use std::path::Path;

use anyhow::{Context, Result};

use crate::config::{validate_service_name, BoxConfig};
use crate::paths::Paths;
use crate::templates;
use crate::util;

/// Identity and platform binding for a generated per-box repo.
#[derive(Debug, Clone)]
pub struct HostSpec {
    /// Host id — becomes the hostname and the nixosConfigurations attr name.
    pub id: String,
    /// Flake ref for the Box platform (`the-box` input): the update channel on
    /// a real Box, or a `path:`/`git+file:` ref for local builds.
    pub platform_ref: String,
    /// Nix system double, e.g. "x86_64-linux".
    pub system: String,
    /// Hardware board (`pi3`/`pi4`/`pi5`), or `None` for the generic appliance.
    /// The platform's `lib.boxSystem` composes the matching vendor kernel,
    /// firmware and boot method — a Pi rebuilt without its board would not
    /// boot. See [`crate::board`].
    pub board: Option<String>,
    /// Whether this box picks up new platform releases on a timer. Rendered
    /// into the host module as `services.the-box.autoUpdate.enable`, which is
    /// what actually creates the timer — without this the console's
    /// "automatic updates" checkbox wrote a value nothing ever read.
    pub auto_update: bool,
}

impl HostSpec {
    pub fn new(
        id: impl Into<String>,
        platform_ref: impl Into<String>,
        system: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            platform_ref: platform_ref.into(),
            system: system.into(),
            board: None,
            auto_update: false,
        }
    }

    pub fn with_board(mut self, board: Option<String>) -> Self {
        self.board = board;
        self
    }

    pub fn with_auto_update(mut self, auto_update: bool) -> Self {
        self.auto_update = auto_update;
        self
    }
}

/// Host ids share the constraints of service names (they become a hostname and
/// a Nix attribute name) with the extra hostname rule that they can't be purely
/// numeric — reuse the service-name validator, which already covers the shape.
pub fn validate_host_id(id: &str) -> Result<()> {
    validate_service_name(id).with_context(|| format!("invalid host id {id:?}"))
}

fn render_flake(spec: &HostSpec) -> String {
    let board = match &spec.board {
        Some(b) => format!("\"{b}\""),
        None => "null".to_string(),
    };
    format!(
        r#"{{
  description = "The Box — configuration for {id} (managed by boxd; do not edit by hand)";

  # The platform is the Box's update channel: boxd, the base OS and the
  # template library, pinned. nixpkgs follows it so the whole box stays
  # coherent with the platform it was built against.
  inputs.the-box.url = "{platform_ref}";
  inputs.nixpkgs.follows = "the-box/nixpkgs";

  outputs = {{ self, nixpkgs, the-box, ... }}:
    {{
      # boxSystem composes the right hardware layer for this box's board —
      # vendor kernel/firmware/boot on a Raspberry Pi, the generic appliance
      # elsewhere. The platform decides how, so the update path can never
      # drift from the install images.
      nixosConfigurations."{id}" = the-box.lib.boxSystem {{
        system = "{system}";
        board = {board};
        modules = [ ./nodes/hosts/{id} ];
      }};
    }};
}}
"#,
        id = spec.id,
        platform_ref = spec.platform_ref,
        system = spec.system,
        board = board,
    )
}

fn render_host_module(spec: &HostSpec) -> String {
    format!(
        r#"# generated by boxd — host {id}
# Identity plus auto-discovered, box.toml-compiled service modules. Drop a
# .nix file in services/ and it joins the system on the next build.
{{ lib, ... }}:
let
  servicesDir = ./services;
  serviceModules = lib.optionals (builtins.pathExists servicesDir) (
    map (name: servicesDir + "/${{name}}") (
      builtins.filter (lib.hasSuffix ".nix") (
        builtins.attrNames (builtins.readDir servicesDir)
      )
    )
  );
in
{{
  imports = serviceModules;

  networking.hostName = "{id}";
  services.the-box.autoUpdate.enable = {auto_update};
}}
"#,
        id = spec.id,
        auto_update = if spec.auto_update { "true" } else { "false" },
    )
}

/// Write the whole per-box repo under `out_dir` (emptied first):
/// ```text
/// flake.nix
/// nodes/hosts/<id>/default.nix
/// nodes/hosts/<id>/services/<name>.nix        (compiled module)
/// nodes/hosts/<id>/services/<name>/www/...     (materialized content)
/// ```
pub fn write_host_repo(
    paths: &Paths,
    config: &BoxConfig,
    spec: &HostSpec,
    out_dir: &Path,
) -> Result<()> {
    validate_host_id(&spec.id)?;

    // Preserve the platform pin across regeneration: a routine deploy rewrites
    // the sources but must not silently re-resolve the channel. Only an
    // explicit `channel update` bumps flake.lock.
    let saved_lock = std::fs::read(out_dir.join("flake.lock")).ok();

    util::remove_dir_all_forced(out_dir)?;
    let host_dir = out_dir.join("nodes").join("hosts").join(&spec.id);
    let services_dir = host_dir.join("services");
    std::fs::create_dir_all(&services_dir)
        .with_context(|| format!("creating {}", services_dir.display()))?;

    std::fs::write(out_dir.join("flake.nix"), render_flake(spec))?;
    std::fs::write(host_dir.join("default.nix"), render_host_module(spec))?;

    for service in &config.services {
        validate_service_name(&service.name)?;
        let Some(template) = templates::get(&service.template) else {
            anyhow::bail!(
                "service {:?} uses unknown template {:?}",
                service.name,
                service.template
            );
        };

        // Fold domain, allocated port and encrypted env file into params, the
        // same way the fast path does — this tier is the one that actually
        // runs the service, so a missing port or secret here is fatal in a way
        // it never was there.
        let params = crate::nixgen::module_params(paths, service, &services_dir)?;

        std::fs::write(
            services_dir.join(format!("{}.nix", service.name)),
            template.nix_module(&service.name, &params),
        )?;

        // Content: prefer the live source tree; fall back to re-materializing
        // from params (e.g. a config restored without its sources).
        let www = services_dir.join(&service.name).join("www");
        let source = paths.source_dir(&service.name);
        if source.is_dir() {
            util::copy_dir_recursive(&source, &www)?;
        } else {
            template.materialize(&params, &www)?;
        }
    }

    if let Some(lock) = saved_lock {
        std::fs::write(out_dir.join("flake.lock"), lock)?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::ServiceConfig;
    use chrono::Utc;
    use tempfile::TempDir;

    fn sample_config() -> BoxConfig {
        BoxConfig {
            services: vec![ServiceConfig {
                name: "blog".into(),
                template: "static-site".into(),
                params: serde_json::json!({ "index_html": "<h1>hi</h1>" }),
                domain: Some("blog.example.com".into()),
                public: true,
                port: None,
                created_at: Utc::now(),
            }],
            ..Default::default()
        }
    }

    #[test]
    fn generates_composable_repo() {
        let tmp = TempDir::new().unwrap();
        let paths = Paths::new(tmp.path().join("data"));
        paths.ensure().unwrap();
        let out = tmp.path().join("repo");
        let spec = HostSpec::new(
            "demo-box",
            "github:fluxoz/the-box",
            "x86_64-linux",
        );

        write_host_repo(&paths, &sample_config(), &spec, &out).unwrap();

        let flake = std::fs::read_to_string(out.join("flake.nix")).unwrap();
        assert!(flake.contains(r#"nixosConfigurations."demo-box""#));
        // Composition goes through the platform's boxSystem builder, which
        // picks the hardware layer from the board.
        assert!(flake.contains("the-box.lib.boxSystem"));
        assert!(flake.contains("board = null;"));
        assert!(flake.contains(r#"inputs.the-box.url = "github:fluxoz/the-box""#));

        let host = std::fs::read_to_string(out.join("nodes/hosts/demo-box/default.nix")).unwrap();
        assert!(host.contains(r#"networking.hostName = "demo-box""#));

        // Compiled service module + materialized content, domain folded in.
        let module =
            std::fs::read_to_string(out.join("nodes/hosts/demo-box/services/blog.nix")).unwrap();
        assert!(module.contains(r#"services.the-box.sites."blog""#));
        assert!(module.contains("root = ./blog/www;"));
        assert!(module.contains(r#"domain = "blog.example.com";"#));
        assert_eq!(
            std::fs::read_to_string(out.join("nodes/hosts/demo-box/services/blog/www/index.html"))
                .unwrap(),
            "<h1>hi</h1>"
        );
    }

    #[test]
    fn rejects_bad_host_id() {
        assert!(validate_host_id("Good-Box").is_err());
        assert!(validate_host_id("box-1").is_ok());
    }

    /// A Pi's generated flake carries its board, so the platform composes the
    /// vendor kernel/boot instead of the generic appliance (which won't boot it).
    #[test]
    fn pi_board_lands_in_the_flake() {
        let tmp = TempDir::new().unwrap();
        let paths = Paths::new(tmp.path().join("data"));
        paths.ensure().unwrap();
        let out = tmp.path().join("repo");
        let spec = HostSpec::new("box", "github:fluxoz/the-box", "aarch64-linux")
            .with_board(Some("pi5".into()));

        write_host_repo(&paths, &BoxConfig::default(), &spec, &out).unwrap();

        let flake = std::fs::read_to_string(out.join("flake.nix")).unwrap();
        assert!(flake.contains("the-box.lib.boxSystem"));
        assert!(flake.contains(r#"board = "pi5";"#));
        assert!(flake.contains(r#"system = "aarch64-linux";"#));
    }

    /// The OS tier is the one that actually runs a container, so its module
    /// must carry the platform-allocated port and the service's encrypted env
    /// file. Rendering only the domain here meant every app and container
    /// compiled with `port = 0` — nginx proxying to `127.0.0.1:0` and a
    /// database with no password.
    #[test]
    fn os_tier_module_carries_port_and_secrets() {
        let tmp = TempDir::new().unwrap();
        let paths = Paths::new(tmp.path().join("data"));
        paths.ensure().unwrap();
        let secrets = paths.data_dir.join("secrets");
        std::fs::create_dir_all(&secrets).unwrap();
        std::fs::write(secrets.join("db-env.age"), b"ciphertext").unwrap();

        let config = BoxConfig {
            services: vec![ServiceConfig {
                name: "db".into(),
                template: "container".into(),
                params: serde_json::json!({ "image": "postgres:16", "expose": "internal" }),
                domain: None,
                public: false,
                port: Some(8042),
                created_at: Utc::now(),
            }],
            ..Default::default()
        };

        let out = tmp.path().join("repo");
        let spec = HostSpec::new("demo-box", "path:/platform", "x86_64-linux");
        write_host_repo(&paths, &config, &spec, &out).unwrap();

        let module = std::fs::read_to_string(
            out.join("nodes/hosts/demo-box/services/db.nix"),
        )
        .unwrap();
        assert!(module.contains("port = 8042;"), "port must be real: {module}");
        assert!(!module.contains("port = 0;"), "port must not be 0: {module}");
        assert!(
            module.contains("secretEnvFile = ./db-env.age;"),
            "module must point at its secrets: {module}"
        );
        assert!(
            out.join("nodes/hosts/demo-box/services/db-env.age").exists(),
            "the encrypted env file must ship with the module"
        );
    }

    #[test]
    fn preserves_flake_lock_across_regeneration() {
        let tmp = TempDir::new().unwrap();
        let paths = Paths::new(tmp.path().join("data"));
        paths.ensure().unwrap();
        let out = tmp.path().join("repo");
        let spec = HostSpec::new("demo-box", "path:/platform", "x86_64-linux");

        write_host_repo(&paths, &sample_config(), &spec, &out).unwrap();
        // A deploy must not silently re-resolve the platform pin.
        std::fs::write(out.join("flake.lock"), r#"{"pinned":"v1"}"#).unwrap();
        write_host_repo(&paths, &BoxConfig::default(), &spec, &out).unwrap();
        assert_eq!(
            std::fs::read_to_string(out.join("flake.lock")).unwrap(),
            r#"{"pinned":"v1"}"#
        );
    }
}
