use std::fs;
use std::path::PathBuf;

use anyhow::{Context, Result};
use chrono::Utc;

use crate::config::BoxConfig;
use crate::manifest::{Manifest, ManifestService, MANIFEST_FILE};
use crate::paths::Paths;
use crate::templates;
use crate::util;

const FLAKE_TEMPLATE: &str = r#"{
  description = "The Box generation (machine-generated by boxd; do not edit)";

  inputs.nixpkgs.url = "@NIXPKGS@";

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" ];
    in
    {
      packages = nixpkgs.lib.genAttrs systems (system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
        in
        {
          default = pkgs.runCommand "box-generation" { } ''
            mkdir -p "$out/services"
            cp ${./manifest.json} "$out/manifest.json"
@COPIES@          '';
        });
    };
}
"#;

/// Fold a service's resolved state into the params its Nix module is rendered
/// from: its domain, the port the platform allocated it, and a pointer to its
/// encrypted env file (copied into `module_dir` so it ships beside the module).
///
/// Both tiers render modules from the same templates, so both must fold the
/// same things. When only the fast path did this, the OS tier — the tier that
/// actually runs containers and apps — compiled every one of them with
/// `port = 0` and no secrets: nginx proxying to `127.0.0.1:0`, and a database
/// with no password.
pub fn module_params(
    paths: &Paths,
    service: &crate::config::ServiceConfig,
    module_dir: &std::path::Path,
) -> Result<serde_json::Value> {
    let mut params = service.params.clone();
    if let Some(obj) = params.as_object_mut() {
        if let Some(domain) = &service.domain {
            obj.entry("domain")
                .or_insert_with(|| serde_json::Value::String(domain.clone()));
        }
        if let Some(port) = service.port {
            obj.insert("port".into(), serde_json::Value::from(port));
        }
        // Whether the operator published this. It decides which nginx listener
        // serves it — the one your own network reaches, or the one the tunnel
        // does — so it has to travel with the service into the OS tier. It used
        // to stop at the manifest, which is how a service nobody published was
        // still served to the internet.
        obj.insert("public".into(), serde_json::Value::Bool(service.public));
    }

    let age_src = paths
        .data_dir
        .join("secrets")
        .join(format!("{}-env.age", service.name));
    if age_src.exists() {
        fs::create_dir_all(module_dir)?;
        fs::copy(
            &age_src,
            module_dir.join(format!("{}-env.age", service.name)),
        )?;
        if let Some(obj) = params.as_object_mut() {
            obj.insert(
                "secret_env_file".into(),
                serde_json::Value::String(format!("./{}-env.age", service.name)),
            );
        }
    }
    Ok(params)
}

/// Write the generation source directory: the immutable tree to build
/// (manifest + per-service content) plus a machine-generated flake that
/// assembles it into a Nix store path. The local (non-Nix) backend uses the
/// same directory and simply ignores the flake.
pub fn write_gensrc(paths: &Paths, config: &BoxConfig) -> Result<PathBuf> {
    let gensrc = paths.gensrc_dir();
    util::remove_dir_all_forced(&gensrc)?;
    fs::create_dir_all(&gensrc).with_context(|| format!("creating {}", gensrc.display()))?;

    let manifest = Manifest {
        schema: 1,
        created_at: Utc::now(),
        services: config
            .services
            .iter()
            .map(|s| ManifestService {
                name: s.name.clone(),
                template: s.template.clone(),
                params: s.params.clone(),
                domain: s.domain.clone(),
                public: s.public,
                port: s.port,
                exposure: templates::get(&s.template)
                    .map(|t| t.exposure(&s.params).as_str().to_string())
                    .unwrap_or_default(),
            })
            .collect(),
        config_toml: config.to_toml()?,
    };
    fs::write(
        gensrc.join(MANIFEST_FILE),
        serde_json::to_string_pretty(&manifest)?,
    )?;

    // Compile each service into a dendritic host module (compile-to-module).
    // boxd's fast path builds the content directly below; these modules are
    // the artifact the OS tier and dashboard introspection read.
    let modules_dir = gensrc.join("modules");
    fs::create_dir_all(&modules_dir)?;
    for service in &config.services {
        if let Some(t) = templates::get(&service.template) {
            let params = module_params(paths, service, &modules_dir)?;
            fs::write(
                modules_dir.join(format!("{}.nix", service.name)),
                t.nix_module(&service.name, &params),
            )?;
        }
    }

    // Only file-backed services have a tree to copy. Process-backed ones
    // (containers, reverse-proxied apps) materialize nothing, and the flake
    // must not reference a path that was never written — `${./services/x/www}`
    // for a missing directory is an EVAL error, which failed the build of any
    // generation containing a container.
    let mut with_content = Vec::new();
    for service in &config.services {
        let source = paths.source_dir(&service.name);
        if source.is_dir() {
            util::copy_dir_recursive(
                &source,
                &gensrc.join("services").join(&service.name).join("www"),
            )?;
            with_content.push(service.name.clone());
        }
    }

    fs::write(gensrc.join("flake.nix"), render_flake(&with_content))?;
    Ok(gensrc)
}

/// Which nixpkgs a generation builds against.
///
/// On a Box the platform hands us the exact store path its own system was built
/// from (`BOX_NIXPKGS`), so a generation pins to nixpkgs already on this disk:
/// no network, no registry, and the same inputs every time. Off a Box (a dev
/// machine) fall back to the registry's `nixpkgs`.
fn nixpkgs_url() -> String {
    nixpkgs_url_from(std::env::var("BOX_NIXPKGS").ok().as_deref())
}

fn nixpkgs_url_from(configured: Option<&str>) -> String {
    match configured.map(str::trim) {
        Some(path) if !path.is_empty() => format!("path:{path}"),
        _ => "flake:nixpkgs".to_string(),
    }
}

/// Render the generation flake. `with_content` is the set of services whose
/// `www` tree was actually written next to it — never the whole service list.
fn render_flake(with_content: &[String]) -> String {
    let mut copies = String::new();
    for name in with_content {
        // Names are validated to [a-z0-9-], safe to splice into Nix code.
        copies.push_str(&format!(
            "            mkdir -p \"$out/services/{name}\"\n            cp -r ${{./services/{name}/www}} \"$out/services/{name}/www\"\n"
        ));
    }
    FLAKE_TEMPLATE
        .replace("@COPIES@", &copies)
        .replace("@NIXPKGS@", &nixpkgs_url())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::ServiceConfig;

    fn service(name: &str, template: &str, params: serde_json::Value) -> ServiceConfig {
        ServiceConfig {
            name: name.into(),
            template: template.into(),
            params,
            domain: None,
            public: false,
            port: None,
            repo: None,
            created_at: Utc::now(),
        }
    }

    #[test]
    fn flake_lists_each_service() {
        let flake = render_flake(&["blog".to_string()]);
        assert!(flake.contains("cp -r ${./services/blog/www}"));
        // Off a Box, nixpkgs comes from the registry.
        assert!(flake.contains("nixpkgs.url = \"flake:nixpkgs\""), "{flake}");
    }

    /// On a Box the platform tells boxd which nixpkgs it was built from, and a
    /// generation pins to that store path — so building one needs no network
    /// and can't drift onto a different nixpkgs than the closure already here.
    #[test]
    fn generation_pins_the_platform_nixpkgs() {
        assert_eq!(
            nixpkgs_url_from(Some("/nix/store/abc-source")),
            "path:/nix/store/abc-source"
        );
        assert_eq!(nixpkgs_url_from(Some("  ")), "flake:nixpkgs");
        assert_eq!(nixpkgs_url_from(None), "flake:nixpkgs");
    }

    /// The flake may only reference trees that were actually written. A
    /// container materializes no `www`, and `${./services/<name>/www}` for a
    /// path that does not exist is an eval error — which used to fail the build
    /// of every generation containing a container or app, on any Box with Nix.
    #[test]
    fn flake_only_copies_services_that_have_content() {
        let tmp = tempfile::TempDir::new().unwrap();
        let paths = crate::paths::Paths::new(tmp.path().to_path_buf());
        paths.ensure().unwrap();

        let config = BoxConfig {
            services: vec![
                service("blog", "static-site", serde_json::json!({})),
                service(
                    "db",
                    "container",
                    serde_json::json!({ "image": "postgres:16", "expose": "internal" }),
                ),
                service(
                    "api",
                    "reverse-proxied-app",
                    serde_json::json!({ "command": "serve" }),
                ),
            ],
            ..Default::default()
        };

        // Materialize like a real deploy: only the static site writes a tree.
        for s in &config.services {
            let t = crate::templates::get(&s.template).unwrap();
            t.materialize(&s.params, &paths.source_dir(&s.name))
                .unwrap();
        }

        let gensrc = write_gensrc(&paths, &config).unwrap();
        let flake = std::fs::read_to_string(gensrc.join("flake.nix")).unwrap();

        assert!(flake.contains("cp -r ${./services/blog/www}"));
        for absent in ["db", "api"] {
            assert!(
                !flake.contains(&format!("services/{absent}/www")),
                "flake references a tree that was never written for {absent}: {flake}"
            );
            assert!(
                !gensrc.join("services").join(absent).join("www").exists(),
                "{absent} should not have materialized a www tree"
            );
        }
        // Every service still compiles to a module regardless of content.
        for s in ["blog", "db", "api"] {
            assert!(gensrc.join("modules").join(format!("{s}.nix")).exists());
        }
    }

    #[test]
    fn secret_env_file_is_shipped_and_referenced() {
        let tmp = tempfile::TempDir::new().unwrap();
        let paths = crate::paths::Paths::new(tmp.path().to_path_buf());
        paths.ensure().unwrap();
        // A pre-existing encrypted env file for service "web".
        let secrets = paths.data_dir.join("secrets");
        std::fs::create_dir_all(&secrets).unwrap();
        std::fs::write(secrets.join("web-env.age"), b"ciphertext").unwrap();

        let config = BoxConfig {
            services: vec![ServiceConfig {
                name: "web".into(),
                template: "container".into(),
                params: serde_json::json!({ "image": "nginx", "container_port": 80 }),
                domain: None,
                public: false,
                port: Some(8000),
                repo: None,
                created_at: Utc::now(),
            }],
            ..Default::default()
        };
        let gensrc = write_gensrc(&paths, &config).unwrap();
        // The .age is shipped next to the module, and the module points at it.
        assert!(gensrc.join("modules/web-env.age").exists());
        let module = std::fs::read_to_string(gensrc.join("modules/web.nix")).unwrap();
        assert!(
            module.contains("secretEnvFile = ./web-env.age;"),
            "module should reference the secret env file: {module}"
        );
    }
}
