use std::fs;
use std::path::PathBuf;

use anyhow::{Context, Result};
use chrono::Utc;

use crate::config::BoxConfig;
use crate::manifest::{Manifest, ManifestService, MANIFEST_FILE};
use crate::paths::Paths;
use crate::templates;
use crate::util;

const FLAKE_TEMPLATE: &str = r#"{
  description = "The Box generation (machine-generated by boxd; do not edit)";

  inputs.nixpkgs.url = "flake:nixpkgs";

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" ];
    in
    {
      packages = nixpkgs.lib.genAttrs systems (system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
        in
        {
          default = pkgs.runCommand "box-generation" { } ''
            mkdir -p "$out/services"
            cp ${./manifest.json} "$out/manifest.json"
@COPIES@          '';
        });
    };
}
"#;

/// Write the generation source directory: the immutable tree to build
/// (manifest + per-service content) plus a machine-generated flake that
/// assembles it into a Nix store path. The local (non-Nix) backend uses the
/// same directory and simply ignores the flake.
pub fn write_gensrc(paths: &Paths, config: &BoxConfig) -> Result<PathBuf> {
    let gensrc = paths.gensrc_dir();
    util::remove_dir_all_forced(&gensrc)?;
    fs::create_dir_all(&gensrc).with_context(|| format!("creating {}", gensrc.display()))?;

    let manifest = Manifest {
        schema: 1,
        created_at: Utc::now(),
        services: config
            .services
            .iter()
            .map(|s| ManifestService {
                name: s.name.clone(),
                template: s.template.clone(),
                params: s.params.clone(),
                domain: s.domain.clone(),
                public: s.public,
                port: s.port,
                exposure: templates::get(&s.template)
                    .map(|t| t.exposure(&s.params).as_str().to_string())
                    .unwrap_or_default(),
            })
            .collect(),
        config_toml: config.to_toml()?,
    };
    fs::write(
        gensrc.join(MANIFEST_FILE),
        serde_json::to_string_pretty(&manifest)?,
    )?;

    // Compile each service into a dendritic host module (compile-to-module).
    // boxd's fast path builds the content directly below; these modules are
    // the artifact the OS tier and dashboard introspection read.
    let modules_dir = gensrc.join("modules");
    fs::create_dir_all(&modules_dir)?;
    for service in &config.services {
        if let Some(t) = templates::get(&service.template) {
            let mut params = service.params.clone();
            if let Some(obj) = params.as_object_mut() {
                if let Some(domain) = &service.domain {
                    obj.entry("domain")
                        .or_insert_with(|| serde_json::Value::String(domain.clone()));
                }
                if let Some(port) = service.port {
                    obj.insert("port".into(), serde_json::Value::from(port));
                }
            }
            fs::write(
                modules_dir.join(format!("{}.nix", service.name)),
                t.nix_module(&service.name, &params),
            )?;
        }
    }

    for service in &config.services {
        // Process-backed services (reverse-proxied apps) have no file tree; only
        // file services materialize a www directory to copy.
        let source = paths.source_dir(&service.name);
        if source.is_dir() {
            util::copy_dir_recursive(
                &source,
                &gensrc.join("services").join(&service.name).join("www"),
            )?;
        }
    }

    fs::write(gensrc.join("flake.nix"), render_flake(config))?;
    Ok(gensrc)
}

fn render_flake(config: &BoxConfig) -> String {
    let mut copies = String::new();
    for service in &config.services {
        // Names are validated to [a-z0-9-], safe to splice into Nix code.
        copies.push_str(&format!(
            "            mkdir -p \"$out/services/{name}\"\n            cp -r ${{./services/{name}/www}} \"$out/services/{name}/www\"\n",
            name = service.name
        ));
    }
    FLAKE_TEMPLATE.replace("@COPIES@", &copies)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::ServiceConfig;

    #[test]
    fn flake_lists_each_service() {
        let config = BoxConfig {
            services: vec![ServiceConfig {
                name: "blog".into(),
                template: "static-site".into(),
                params: serde_json::json!({}),
                domain: None,
                public: false,
                port: None,
                created_at: Utc::now(),
            }],
            ..Default::default()
        };
        let flake = render_flake(&config);
        assert!(flake.contains("cp -r ${./services/blog/www}"));
        assert!(flake.contains("flake:nixpkgs"));
    }
}
