//! Template registry. A service is "a template + params": the template knows
//! how to validate its params, materialize the service's content, and emit a
//! dendritic Nix module for the OS tier. Static-site is template #1; the GUI
//! catalog and the agent tools install any registered template the same way.

use std::path::Path;

use anyhow::{bail, Context, Result};
use serde_json::Value;

use crate::util;

pub trait Template: Send + Sync {
    fn id(&self) -> &'static str;
    fn title(&self) -> &'static str;
    fn description(&self) -> &'static str;

    /// Reject params this template can't honor. Runs before anything is written.
    fn validate(&self, params: &Value) -> Result<()>;

    /// Write the service's content into `source_dir` (already emptied).
    fn materialize(&self, params: &Value, source_dir: &Path) -> Result<()>;

    /// Emit a dendritic host-module snippet describing this service. Not yet
    /// the build driver (boxd's fast path builds the content directly); this
    /// is the compile-to-module artifact the OS tier and introspection use.
    fn nix_module(&self, name: &str, params: &Value) -> String;

    /// A generation is healthy if every service's expected outputs exist.
    /// Checked against the built generation tree before the switch is kept.
    fn health(&self, name: &str, www_dir: &Path) -> Result<()> {
        let _ = (name, www_dir);
        Ok(())
    }
}

/// All templates known to this Box. The GUI catalog renders from this list.
pub fn all() -> &'static [&'static dyn Template] {
    &[&StaticSite]
}

pub fn get(id: &str) -> Option<&'static dyn Template> {
    all().iter().copied().find(|t| t.id() == id)
}

// ---------------------------------------------------------------------------

pub const DEFAULT_INDEX: &str = r#"<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello from The Box</title>
</head>
<body style="font-family: system-ui, sans-serif; display: grid; place-items: center; min-height: 100vh; margin: 0;">
  <div style="text-align: center;">
    <h1>&#128230; It works!</h1>
    <p>This site is served by The Box.</p>
  </div>
</body>
</html>
"#;

/// static-site: serves a directory of files. Params: `index_html` (inline
/// single page) and/or `source_path` (a directory on the Box to copy;
/// wins over `index_html`).
pub struct StaticSite;

impl Template for StaticSite {
    fn id(&self) -> &'static str {
        "static-site"
    }
    fn title(&self) -> &'static str {
        "Static site"
    }
    fn description(&self) -> &'static str {
        "Serve a folder of static files (HTML, CSS, JS, images)."
    }

    fn validate(&self, params: &Value) -> Result<()> {
        if let Some(v) = params.get("index_html") {
            if !v.is_string() {
                bail!("static-site: index_html must be a string");
            }
        }
        if let Some(v) = params.get("source_path") {
            if !v.is_string() {
                bail!("static-site: source_path must be a string");
            }
        }
        Ok(())
    }

    fn materialize(&self, params: &Value, source_dir: &Path) -> Result<()> {
        util::remove_dir_all_forced(source_dir)?;
        std::fs::create_dir_all(source_dir)?;
        if let Some(src) = params.get("source_path").and_then(Value::as_str) {
            let from = std::fs::canonicalize(src)
                .with_context(|| format!("resolving source_path {src}"))?;
            if !from.is_dir() {
                bail!("source_path {} is not a directory", from.display());
            }
            util::copy_dir_recursive(&from, source_dir)?;
        } else {
            let html = params
                .get("index_html")
                .and_then(Value::as_str)
                .unwrap_or(DEFAULT_INDEX);
            std::fs::write(source_dir.join("index.html"), html)?;
        }
        Ok(())
    }

    fn nix_module(&self, name: &str, params: &Value) -> String {
        // Names are validated to [a-z0-9-], safe to splice. This is the OS-tier
        // host-service module: it lives at services/<name>.nix with content
        // alongside at services/<name>/www, and the platform turns it into a
        // real nginx vhost. The same module backs dashboard introspection.
        let domain = params
            .get("domain")
            .and_then(Value::as_str)
            .map(|d| format!("\n    domain = \"{d}\";"))
            .unwrap_or_default();
        format!(
            "# generated by boxd — service {name} (static-site)\n\
             {{ ... }}:\n\
             {{\n  services.the-box.sites.\"{name}\" = {{\n    root = ./{name}/www;{domain}\n  }};\n}}\n"
        )
    }

    fn health(&self, name: &str, www_dir: &Path) -> Result<()> {
        if !www_dir.join("index.html").exists() {
            bail!("service {name:?}: static-site has no index.html to serve");
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use tempfile::TempDir;

    #[test]
    fn registry_lookup() {
        assert!(get("static-site").is_some());
        assert!(get("nope").is_none());
        assert_eq!(all().len(), 1);
    }

    #[test]
    fn static_site_materializes_and_health() {
        let tmp = TempDir::new().unwrap();
        let dir = tmp.path().join("www");
        StaticSite
            .materialize(&json!({"index_html": "<h1>hi</h1>"}), &dir)
            .unwrap();
        assert_eq!(
            std::fs::read_to_string(dir.join("index.html")).unwrap(),
            "<h1>hi</h1>"
        );
        StaticSite.health("s", &dir).unwrap();

        // empty (no index) fails health
        let empty = tmp.path().join("empty");
        std::fs::create_dir_all(&empty).unwrap();
        assert!(StaticSite.health("s", &empty).is_err());
    }

    #[test]
    fn rejects_bad_params() {
        assert!(StaticSite.validate(&json!({"index_html": 5})).is_err());
        assert!(StaticSite.validate(&json!({"source_path": true})).is_err());
        assert!(StaticSite.validate(&json!({"index_html": "ok"})).is_ok());
    }
}
